name: app_tcc
description: Aplicativo desenvolvido para TCC

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^7.0.1
#  geolocator_background: ^3.0.0
  permission_handler: ^10.3.0
  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  google_fonts: ^4.0.4
  http: ^0.13.4
  http_interceptor: ^1.0.2
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.3.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logo/logo.png

  uses-material-design: true



